### PR TITLE
Add 1:1 read note & examples links

### PR DESCRIPTION
**Pull request by noffle**

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Brilliant, thanks!

**Comment by dominictarr** [comment]
lets phrase it more like: if you have a difficulty with pull-streams, don't worry. there is a module for that.

@ahdinosaur what about an FAQ that was like "how do I X" and every answer was links to modules?

**Comment by noffle** [comment]
Yeah, an FAQ would be great! Happy to collab on this.

**Comment by dominictarr** [comment]
okay first thing is a list of questions

**Comment by noffle** [comment]
here were my early questions:

### how can I achieve 1:many and many:1 transforms?

this pr

### how do I interop with node streams? are there any caveats?

1st Q is mentioned in the README, but 2nd isn't. I'm thinking of
good-to-know things like https://twitter.com/dominictarr/status/737566000086802432

(it may be enough to just mention no backpressure in the README of
https://github.com/pull-stream/pull-pushable)

---

the only other struggle I had in learning was just playing with the
examples and grokking the `read`/`cb` flow that takes place, writing my
own sources/sinks/transforms from 1st principles. having a nodeschool
workshopper might be nice -- I might look at that!

**Comment by dominictarr** [comment]
https://github.com/pull-stream/pull-stream-faq

**Pull request merged**
