### PR TITLE
Export pull function like the rest

### PR DESCRIPTION
**Pull request by tjconcept**
To turn:

```js
const pull = require('pull-stream');
const { map, log } = pull;
```

into:

```js
const { pull, map, log } = require('pull-stream');
```

### CODE REVIEW

**Comment by ahdinosaur** [comment]
hey @tjconcept, this is great, thanks!

**Comment by ahdinosaur** [comment]
hey @dominictarr, since you're the only npm owner, is it possible for you to either release this or add more npm owners?

**Comment by dominictarr** [comment]
@ahdinosaur added you

**Comment by dominictarr** [comment]
btw, please post the new version to the issue when releasing a PR

**Comment by ahdinosaur** [comment]
thanks @dominictarr, released as `3.5.1`! :tada:

**Comment by dominictarr** [comment]
@ahdinosaur as a patch? this should have been a feature

**Comment by tjconcept** [comment]
Awesome, thanks @ahdinosaur 

> this should have been a feature

Yeah.. if it's worth it mark this release as bogus an issue a new.

**Comment by ahdinosaur** [comment]
yeah i thought about it, it didn't really feel like a feature it felt like something was fixed rather than added. sorry for making the wrong choice.

**Comment by dominictarr** [comment]
@ahdinosaur it's a tiny thing, but we should rerelease as a matter of principle. just publish it again with the correct number. sure now there are two versions with the same code, that is fine.

**Comment by ahdinosaur** [comment]
@dominictarr sweet as, `3.6.0`!

**Comment by ahdinosaur** [comment]
also unpublished `3.5.1` with `npm unpublish pull-stream@3.5.1` and removed the git tag, was easy enough and i understand should be harmless. sorry folks! :heart:

**Pull request merged**
