### PR TITLE
Add type function.

### PR DESCRIPTION
**Pull request by jamen**
Hello.  I was going to create a module `pull-stream-type`, but it turned out pretty small and is also pretty generally useful, so I thought why not add it to the core?

You use it like this:

```js
var pull = require('pull-stream')
var type = require('pull-stream/util/type')

type(pull.values()) === 'source'
type(pull.map()) === 'through'
type(pull.reduce()) === 'sink'
// Handle improper
type(() => {}) === null
```

This isn't a way to verify streams (I don't think that is even possible).  Just tells you what it is if you are certain it is a stream already.

### CODE REVIEW

**Comment by jamen** [comment]
Side note: I wasn't sure of a good place to put this, `./util` looks like internal stuff.  But it seemed fitting.

**Comment by ahdinosaur** [comment]
hey @jamen, cool!

have you seen [`is-pull-stream`](https://github.com/dominictarr/is-pull-stream)? it's similar, but is missing a check for a through, the `try` / `catch` is an interesting approach.

@dominictarr what are your thoughts on this?

**Comment by jamen** [comment]
I had not seen that, but I tried searching before hand.  :^(  I can do PR there if that would be more appropriate.

Also, I wasn't sure how I wanted to do `'through'`.  Calling it to see if it returns a function breaks if you pass it a source stream, so I had to wrap it with `try`/`catch` here.

**Comment by dominictarr** [comment]
hmm... I'd totally take this for source and sink, it's reasonable for sources and sinks, but it's gonna be quite problematic for throughs: calling the function to see if it is a through could have all sorts of crazy side-effects. Maybe it's safe if it _is_ a through, but if the function is something else, then anything could happen.

So you can have stuff that tests for source or sink, but if you pass a function something that might be a through, and it's not, it's gotta be treated as a programmer error and throw with a good error.

@jamen Would prefer it as `./type.js` i think

**Comment by dominictarr** [comment]
if there was some sort of static analysis in javascript and you could see that the function returned a source without executing it, then that would work, but we don't have that.

**Comment by jamen** [comment]
@dominictarr aha! appears first time I tried I messed up.  Would this be any better?

**Comment by jamen** [comment]
Meh, I guess like you say the strange side effects.  Calling it could be bad if some function that changes some lasting state gets passed in by accident, and lead to hard to debug stuff.

I'll just remove in my update to fix tests.

**Comment by dominictarr** [comment]
@jamen okay cool - oh by the way, have you considered `isSource` `isSink` methods? I mean, you are just gonna end up doing `type(stream) == 'source'` anyway right? this way skips an unnecessary string comparison. I'd like to hear from a few other pull-stream people, pull-stream is important enough a througher discussion is necessary.

**Comment by dominictarr** [comment]
oh, hmm, actually sorry, just realized yes, you do need to write into the sublevel instance to index stuff.
Originally level-sublevel monkeypatched the db, but that changed.

**Comment by jamen** [comment]
@dominictarr I didn't think of that route until seeing `is-pull-stream`.  I did it with strings originally because I thought about handling it in a switch `switch (type(stream)) { ... }` and I was also thinking of JavaScript's `typeof`.

**Comment by jamen** [comment]
Hmm.  I decided that I don't think this is necessary because of `is-pull-stream`.  :stuck_out_tongue:

**Pull request closed without merging**
