### PR TITLE
Improve benchmarks

### PR DESCRIPTION
**Pull request by Barbarrosa**
This PR rewrites the benchmarks to include more useful information about speed, memory usage, and statistical significance of the results.

Example:
```
$ node ./benchmarks/index.js 

flatten x 3,712,871 ops/sec ±1.32% (47 runs sampled)
Heap Change - max: 16.9 MB, min:-16 MB, mean:116 kB, std dev:10.2 MB

node x 6,695 ops/sec ±1.48% (71 runs sampled)
Heap Change - max: 2.52 MB, min:-269 kB, mean:73.6 kB, std dev:329 kB

pull x 85,951 ops/sec ±6.79% (67 runs sampled)
Heap Change - max: 14.8 MB, min:-6.59 MB, mean:90.9 kB, std dev:3.71 MB
```

### CODE REVIEW

**Review by staltz — APPROVED** [review]
Looks good!

**Comment by Barbarrosa** [comment]
@mixmix Let me know if you have feedback for me to address before you merge this PR.

**Comment by staltz** [comment]
PS: we'd really appreciate the statistical significance info on jitdb and ssb-db2 benchmarks too. It's been hard to discern what is normal fluctuation and what is different performance.

**Comment by Barbarrosa** [comment]
I learned while working on ssb-ngi-pointer/jitdb#143 that the measurement of memory during `onCycle` here will capture multiple runs at once, so it may be less precise than desirable. I'm thinking about making another PR to `pull-stream` that uses [nodemark](https://github.com/JoshuaWise/nodemark) for the benchmark w/ a more precise memory measurement.

**Comment by staltz** [comment]
@Barbarrosa I'm now a maintainer here, and there are some git conflicts, could you resolve them? After that, I'm happy to merge it

**Comment by Barbarrosa** [comment]
@staltz I fixed the merge conflicts

**Comment by staltz** [comment]
Thank you @Barbarrosa

**Pull request merged**
