### PR TITLE
(WIP) flatten internal modules

### PR DESCRIPTION
**Pull request by ahdinosaur**
hey pull-stream,

this pull request is to flatten the internal modules of `pull-stream`,
such that they can be required at `require('pull-stream/*')`.

should keep comaptibily with `require('pull-stream/{sources,throughs,sinks}')`.

tests pass, but this probably needs a more thorough overview.

@dominictarr: a question about [this line](https://github.com/pull-stream/pull-stream/blob/master/throughs.js#L10), is that supposed to be `key.exec`?

### CODE REVIEW

**Comment by dominictarr** [comment]
this looks good, i'm gonna merge this but then move `sources.js` to `sources/index.js` and then put all sources inside that directory too. so to require `pull.values` you'll do `require('pull-stream/sources/values')`

**Comment by dominictarr** [comment]
@ahdinosaur you are correct. that link should be key.exec

**Comment by dominictarr** [comment]
okay, I merged into 3.4.0, with some changes:

* everything is moved into directories, so the top level is `index.js`, `pull.js`, `sources/` `sinks/` `throughs/`
* file names are always hypenated instead of camel case. (some fs are case insensitive, easier to just use lower case)
* inlined id function instead of requiring it (it's actually shorter to inline it than use require, I would require a one line function if it was more complicated, though)
* fixed a few spots where something was missing (`id`, in one or two places, I guess there isn't test coverage for this );
* made everything `'use strict'`

thanks!

**Comment by ahdinosaur** [comment]
sweeeeeeet, that's awesome, thanks @dominictarr! :smile: 

just as a friendly reminder, you may have forgotten to push these changes to GitHub, churrrrr.

**Comment by dominictarr** [comment]
oh, sorry - it was pushed to dominictarr/pull-stream, forgot to update my remote. fixed now.

**Comment by yoshuawuyts** [comment]
yay!

**Comment by dominictarr** [comment]
feel free to put in pull requests to other pull-* modules to require just the functions they use

**Pull request closed without merging**
