### PR TITLE
Update random number stream example.

### PR DESCRIPTION
**Pull request by nrn**
Moving the counter state inside the function that creates the random stream illustrates how easy it is to set up stream local state. Each instance of the random stream will now give out 100 random numbers, instead of all random streams giving out a total of 100 numbers.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
I think this is quite reasonable; closer to a real world component I reckon

**Comment by dominictarr** [comment]
even better would be to pass in i as an argument.

**Comment by dominictarr** [comment]
@nrn merged into 3.4.3

**Comment by nrn** [comment]
Thanks! Passing in the count is an even more useful example.

**Pull request merged**
